# Generated by Django 3.2.7 on 2021-09-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['cart_id']},
        ),
    ]
